# Generated by Django 4.2.5 on 2023-10-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deckName', models.CharField(default='New Deck', max_length=50)),
                ('owner', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(default='', max_length=200)),
                ('text', models.TextField(default='')),
                ('type', models.CharField(default='', max_length=50)),
                ('colors', models.CharField(default='', max_length=10)),
                ('decks', models.ManyToManyField(to='test_app.deck')),
            ],
        ),
    ]
