# Generated by Django 4.2.5 on 2023-10-07 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='card',
            name='decks',
        ),
        migrations.RemoveField(
            model_name='card',
            name='text',
        ),
        migrations.RemoveField(
            model_name='card',
            name='type',
        ),
        migrations.AddField(
            model_name='card',
            name='scryfallId',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='CardToDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('card', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='test_app.card')),
                ('deck', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='test_app.deck')),
            ],
        ),
    ]
