# Generated by Django 4.2.5 on 2023-09-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='colors',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
