# Generated by Django 4.2.5 on 2023-10-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_remove_card_decks_deck_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cardName',
        ),
        migrations.RemoveField(
            model_name='card',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='card',
            name='text',
        ),
        migrations.RemoveField(
            model_name='card',
            name='type',
        ),
        migrations.AddField(
            model_name='card',
            name='scryfallId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
