# Generated by Django 4.2.5 on 2023-09-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_card_colors_alter_card_cardname_alter_card_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deckName', models.CharField(default='New Deck', max_length=50)),
                ('owner', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(to='test_app.deck'),
        ),
    ]
